SBT Index Correction and updates to instance transform API
gprt-org/GPRT pull request #28
Opened 2022-11-17 15:35 UTC by natevm

This PR corrects a bug breaking multiple BLAS from working in one TLAS

We also change the instance transform API to now properly take count, stride and offset. This enables the use of 4x4 or 3x4 row major transform matrices.

2022-11-17 23:58 UTC, pshriwise requested changes
Some pretty minor comments to start.

2022-11-17 23:58 UTC, pshriwise commented on samples/int08-multipleTLAS/hostCode.cpp
> +  gprtInstanceAccelSetTransforms(tetrahedraTLAS, tetrahedraTransformBuffer, 1, sizeof(float3x4), 0);
What would you think of a couple of higher-level wrappers for this function? Something like 
`gprtInstanceAccelSet3x4Transform`?

2022-11-17 23:58 UTC, pshriwise commented on gprt/gprt.cpp
> +    // size_t count,
There are a lot of comments in these functions/structs. Can we remove them?

2022-11-17 23:58 UTC, pshriwise commented on gprt/gprt.cpp
> +          //  (rather than the host, or in a special host/device section)
```suggestion
          // (rather than the host, or in a special host/device section)
```

2022-11-17 23:58 UTC, pshriwise commented on gprt/gprt.cpp
> +        // }
Remove?

2022-11-17 23:58 UTC, pshriwise commented on gprt/gprt.cpp
> +      throw std::runtime_error("Error, transform count must match number of instances!");
`GPRT_RAISE` here?

2022-11-18 12:24 UTC, pshriwise requested changes
Looking good! Just a few more thoughts.

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt_host.h
> +GPRT_API void
Nice!! This looks a bit easier to use to me. 🤩

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt_device_code.hlsl
> +    int(instanceShaderBindingTableRecordOffset + blasOffset) | 0x00 << 24;
This could use a comment.

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt_device_code.hlsl
> +  // printf("blas %d offset %d\n", DTid.x, instanceShaderBindingTableRecordOffset + blasOffset);
Remove?

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt.cpp
> +      delete(accelBuffer);
Does it make sense to put a `destroy()` call into `~Buffer`? 

Then this can simply be `delete(accelBuffer)`.

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt.cpp
> +    }
This pattern of checking of a buffer size happens in a few places here. Could it be pushed down into the `Buffer` class somehow?

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt.cpp
> +    // size_t offset = 0;
Remove?

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt.cpp
> +      memcpy(this->instances.data(), instances, sizeof(GPRTAccel*) * numInstances);
I'm a little concerned about memory leaks here. Will the `Accel` objects clean themselves up correctly if they're replaced in the vector?

2022-11-18 12:24 UTC, pshriwise commented on gprt/gprt.cpp
> +      delete(accelBuffer);
This could also be done in a subsequent PR.

2022-11-18 14:14 UTC, pshriwise approved these changes

2022-11-18 14:14 UTC, merged

2022-11-18 14:16 UTC, natevm commented
Plan is to move some of these requests into refactoring PRs